/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AadhaarRouteImport } from './routes/aadhaar'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AadhaarRoute = AadhaarRouteImport.update({
  id: '/aadhaar',
  path: '/aadhaar',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aadhaar': typeof AadhaarRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/profile-setup': typeof ProfileSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aadhaar': typeof AadhaarRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/profile-setup': typeof ProfileSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aadhaar': typeof AadhaarRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/profile-setup': typeof ProfileSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aadhaar'
    | '/kyc'
    | '/login'
    | '/onboarding'
    | '/otp'
    | '/profile-setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aadhaar'
    | '/kyc'
    | '/login'
    | '/onboarding'
    | '/otp'
    | '/profile-setup'
  id:
    | '__root__'
    | '/'
    | '/aadhaar'
    | '/kyc'
    | '/login'
    | '/onboarding'
    | '/otp'
    | '/profile-setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AadhaarRoute: typeof AadhaarRoute
  KycRoute: typeof KycRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OtpRoute: typeof OtpRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aadhaar': {
      id: '/aadhaar'
      path: '/aadhaar'
      fullPath: '/aadhaar'
      preLoaderRoute: typeof AadhaarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AadhaarRoute: AadhaarRoute,
  KycRoute: KycRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OtpRoute: OtpRoute,
  ProfileSetupRoute: ProfileSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
