/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AadhaarRouteImport } from './routes/aadhaar'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as CooperativesRouteImport } from './routes/cooperatives'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as QrVerifyRouteImport } from './routes/qr-verify'
import { Route as ServiceAreaRouteImport } from './routes/service-area'
import { Route as SkillVerificationRouteImport } from './routes/skill-verification'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as WorkerIdRouteImport } from './routes/worker-id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AadhaarRoute = AadhaarRouteImport.update({
  id: '/aadhaar',
  path: '/aadhaar',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const CooperativesRoute = CooperativesRouteImport.update({
  id: '/cooperatives',
  path: '/cooperatives',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const QrVerifyRoute = QrVerifyRouteImport.update({
  id: '/qr-verify',
  path: '/qr-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreaRoute = ServiceAreaRouteImport.update({
  id: '/service-area',
  path: '/service-area',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillVerificationRoute = SkillVerificationRouteImport.update({
  id: '/skill-verification',
  path: '/skill-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerIdRoute = WorkerIdRouteImport.update({
  id: '/worker-id',
  path: '/worker-id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aadhaar': typeof AadhaarRoute
  '/availability': typeof AvailabilityRoute
  '/cooperatives': typeof CooperativesRoute
  '/dashboard': typeof DashboardRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/qr-verify': typeof QrVerifyRoute
  '/service-area': typeof ServiceAreaRoute
  '/skill-verification': typeof SkillVerificationRoute
  '/skills': typeof SkillsRoute
  '/worker-id': typeof WorkerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aadhaar': typeof AadhaarRoute
  '/availability': typeof AvailabilityRoute
  '/cooperatives': typeof CooperativesRoute
  '/dashboard': typeof DashboardRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/qr-verify': typeof QrVerifyRoute
  '/service-area': typeof ServiceAreaRoute
  '/skill-verification': typeof SkillVerificationRoute
  '/skills': typeof SkillsRoute
  '/worker-id': typeof WorkerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aadhaar': typeof AadhaarRoute
  '/availability': typeof AvailabilityRoute
  '/cooperatives': typeof CooperativesRoute
  '/dashboard': typeof DashboardRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/qr-verify': typeof QrVerifyRoute
  '/service-area': typeof ServiceAreaRoute
  '/skill-verification': typeof SkillVerificationRoute
  '/skills': typeof SkillsRoute
  '/worker-id': typeof WorkerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aadhaar'
    | '/availability'
    | '/cooperatives'
    | '/dashboard'
    | '/kyc'
    | '/login'
    | '/onboarding'
    | '/otp'
    | '/profile-setup'
    | '/qr-verify'
    | '/service-area'
    | '/skill-verification'
    | '/skills'
    | '/worker-id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aadhaar'
    | '/availability'
    | '/cooperatives'
    | '/dashboard'
    | '/kyc'
    | '/login'
    | '/onboarding'
    | '/otp'
    | '/profile-setup'
    | '/qr-verify'
    | '/service-area'
    | '/skill-verification'
    | '/skills'
    | '/worker-id'
  id:
    | '__root__'
    | '/'
    | '/aadhaar'
    | '/availability'
    | '/cooperatives'
    | '/dashboard'
    | '/kyc'
    | '/login'
    | '/onboarding'
    | '/otp'
    | '/profile-setup'
    | '/qr-verify'
    | '/service-area'
    | '/skill-verification'
    | '/skills'
    | '/worker-id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AadhaarRoute: typeof AadhaarRoute
  AvailabilityRoute: typeof AvailabilityRoute
  CooperativesRoute: typeof CooperativesRoute
  DashboardRoute: typeof DashboardRoute
  KycRoute: typeof KycRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OtpRoute: typeof OtpRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  QrVerifyRoute: typeof QrVerifyRoute
  ServiceAreaRoute: typeof ServiceAreaRoute
  SkillVerificationRoute: typeof SkillVerificationRoute
  SkillsRoute: typeof SkillsRoute
  WorkerIdRoute: typeof WorkerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aadhaar': {
      id: '/aadhaar'
      path: '/aadhaar'
      fullPath: '/aadhaar'
      preLoaderRoute: typeof AadhaarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cooperatives': {
      id: '/cooperatives'
      path: '/cooperatives'
      fullPath: '/cooperatives'
      preLoaderRoute: typeof CooperativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-verify': {
      id: '/qr-verify'
      path: '/qr-verify'
      fullPath: '/qr-verify'
      preLoaderRoute: typeof QrVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-area': {
      id: '/service-area'
      path: '/service-area'
      fullPath: '/service-area'
      preLoaderRoute: typeof ServiceAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-verification': {
      id: '/skill-verification'
      path: '/skill-verification'
      fullPath: '/skill-verification'
      preLoaderRoute: typeof SkillVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker-id': {
      id: '/worker-id'
      path: '/worker-id'
      fullPath: '/worker-id'
      preLoaderRoute: typeof WorkerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AadhaarRoute: AadhaarRoute,
  AvailabilityRoute: AvailabilityRoute,
  CooperativesRoute: CooperativesRoute,
  DashboardRoute: DashboardRoute,
  KycRoute: KycRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OtpRoute: OtpRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  QrVerifyRoute: QrVerifyRoute,
  ServiceAreaRoute: ServiceAreaRoute,
  SkillVerificationRoute: SkillVerificationRoute,
  SkillsRoute: SkillsRoute,
  WorkerIdRoute: WorkerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
